Feature/firebase login operations
sinansuludag/Asset_Tracker pull request #5
Opened 2024-12-22 16:33 UTC by sinansuludag

2024-12-23 10:28 UTC, E-MRE requested changes
Eklemeler yapıldı

2024-12-23 10:28 UTC, E-MRE commented on android/app/google-services.json
> +{
gitignore ile gizleyelim

2024-12-23 10:28 UTC, E-MRE commented on android/build.gradle
> +// buildscript {
yorum satırı olan yerleri kaldıralım

2024-12-23 10:28 UTC, E-MRE commented on android/app/build.gradle
> +// plugins {
yorum satırlarını silelim

2024-12-23 10:28 UTC, E-MRE commented on android/settings.gradle
> +// pluginManagement {
kullanılmayan kısımları silelim

2024-12-23 10:28 UTC, E-MRE commented on lib/core/exceptions/firebase_auth_exceptions/firebase_error_type.dart
> +  // Authentication Hataları
bu ifadeleri ///Network Error vs vs yaparsak kod yazarken de açıklamalardan takip edebilirsin.

2024-12-23 10:28 UTC, E-MRE commented on lib/core/exceptions/firebase_auth_exceptions/firebase_error_type.dart
> +FirebaseAuthErrorType getErrorTypeFromAuthException(FirebaseAuthException e) {
bunu extension içerisinde yazabiliriz

2024-12-23 10:28 UTC, E-MRE commented on lib/core/mixins/forget_password_screen_mixin.dart
> +  Text bodyText(BuildContext context) {
mixin içerisine widgetları koymamıza gerek yok aslında buraya daha çok değişkenler, fonksiyonlar eklenebilir.

2024-12-23 10:28 UTC, E-MRE commented on lib/core/mixins/login_screen_mixin.dart
> +    return ElevatedButton(
Bu buton login için özelleştirilebilir. LoginButton şeklinde, dışarıdan future fonksiyon alır. vs vs

2024-12-23 10:28 UTC, E-MRE commented on lib/core/mixins/register_screen_mixin.dart
> +    return ElevatedButton(
login için söylediklerim bunun içinde geçerli

2024-12-23 10:28 UTC, E-MRE commented on lib/features/auth/data/datasources/local/local_storage_service.dart
> +class LocalStorageService {
abstract sınıf kullanalım.

2024-12-23 10:28 UTC, E-MRE commented on lib/features/auth/data/datasources/remote/auth_service.dart
> +class FirebaseAuthService {
abstract sınıf kullanalım

2024-12-23 10:57 UTC, sinansuludag commented on android/app/google-services.json
> +{
Gizlediğimi düşünmüştüm herhalde yanlış yapmışım.

2024-12-24 09:43 UTC, merged

2024-12-24 09:43 UTC, sinansuludag commented
firebase operations